require("mrnobody.plugins-setup")
require("mrnobody.core.options")
require("mrnobody.core.keymaps")
require("mrnobody.core.colorscheme")
require("mrnobody.plugin.comment")
require("mrnobody.plugin.nvim-tree")
require("mrnobody.plugin.lualine")
require("mrnobody.plugin.telescope")
require("mrnobody.plugin.nvim-cmp")
require("mrnobody.plugin.lsp.lspconfig")
require("mrnobody.plugin.lsp.lspsaga")
require("mrnobody.plugin.lsp.mason")
require("mrnobody.plugin.lsp.null-ls")
require("mrnobody.plugin.autopairs")
require("mrnobody.plugin.treesitter")
require("mrnobody.plugin.gitsigns")
require("mrnobody.plugin.material-icon")

